// herausforderungen_liste.js
export const herausforderung_liste = [
    {
        name: "Labyrinthstart",
        beschreibung: "Lerne die Grundlagen und bewege PacMan sicher durch das Labyrinth.",
        players: 1,
        map: "original",
        difficulty: "easy",
        anz_ghosts: 1,
        theme: "original",
        reward_exp: 5,
        ghosts_dead: false,
        ghosts_reproduction: false,
        teleporter_aktiv: false,
        teleporter_pacman: false,
        teleporter_ghosts: false,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Doppelte Gefahr",
        beschreibung: "Zwei Geister treiben ihr Unwesen – teste deine Reflexe.",
        players: 1,
        map: "original",
        difficulty: "easy",
        anz_ghosts: 2,
        theme: "forest",
        reward_exp: 5,
        ghosts_dead: false,
        ghosts_reproduction: false,
        teleporter_aktiv: false,
        teleporter_pacman: false,
        teleporter_ghosts: false,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Teleport-Test",
        beschreibung: "Ein Teleporter erscheint – nutze ihn oder weiche aus.",
        players: 1,
        map: "original",
        difficulty: "easy",
        anz_ghosts: 2,
        theme: "lava",
        reward_exp: 5,
        ghosts_dead: false,
        ghosts_reproduction: false,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: false,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Versteckte Fallen",
        beschreibung: "Enge Gänge, schnelle Entscheidungen notwendig.",
        players: 1,
        map: "fogmaze",
        difficulty: "easy",
        anz_ghosts: 3,
        theme: "fog",
        reward_exp: 10,
        ghosts_dead: false,
        ghosts_reproduction: false,
        teleporter_aktiv: false,
        teleporter_pacman: false,
        teleporter_ghosts: false,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Powerplay",
        beschreibung: "Powerups stehen bereit – nutze sie, um die Geister zu besiegen.",
        players: 1,
        map: "fogmaze",
        difficulty: "normal",
        anz_ghosts: 3,
        theme: "ice",
        reward_exp: 10,
        ghosts_dead: false,
        ghosts_reproduction: false,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: false,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Schnelle Gegner",
        beschreibung: "Die Geister bewegen sich schneller – konzentriere dich auf das Timing.",
        players: 1,
        map: "crystal",
        difficulty: "normal",
        anz_ghosts: 3,
        theme: "crystal",
        reward_exp: 15,
        ghosts_dead: false,
        ghosts_reproduction: false,
        teleporter_aktiv: true,
        teleporter_pacman: false,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Verstärkung",
        beschreibung: "Die Geister vermehren sich – du musst clever ausweichen.",
        players: 1,
        map: "fogmaze",
        difficulty: "hard",
        anz_ghosts: 4,
        theme: "forest",
        reward_exp: 15,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: false,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Teleporter-Chaos",
        beschreibung: "PacMan kann Teleporter benutzen – nutze sie geschickt, um zu entkommen.",
        players: 1,
        map: "original",
        difficulty: "hard",
        anz_ghosts: 4,
        theme: "lava",
        reward_exp: 20,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Extreme Jagd",
        beschreibung: "Viele Geister und Teleporter – nur Profis schaffen es.",
        players: 1,
        map: "crystal",
        difficulty: "insane",
        anz_ghosts: 5,
        theme: "crystal",
        reward_exp: 25,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Überleben im Nebel",
        beschreibung: "Die Sicht ist eingeschränkt, Geister sind aggressiver, Teleporter überall.",
        players: 1,
        map: "fogmaze",
        difficulty: "insane",
        anz_ghosts: 6,
        theme: "fog",
        reward_exp: 25,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: false,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Meister der Labyrinthe",
        beschreibung: "Alle Tricks, viele Geister, Teleporter, Reproduktion – bist du bereit?",
        players: 1,
        map: "crystal",
        difficulty: "insane",
        anz_ghosts: 8,
        theme: "crystal",
        reward_exp: 50,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Nebelpfade",
        beschreibung: "Die Sicht ist eingeschränkt – konzentriere dich auf die Geisterbewegungen.",
        players: 1,
        map: "fogmaze",
        difficulty: "insane",
        anz_ghosts: 6,
        theme: "fog",
        reward_exp: 55,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Kristalljagd",
        beschreibung: "Schnelle Geister und funkelnde Teleporter – nur Profis schaffen es.",
        players: 1,
        map: "crystal",
        difficulty: "insane",
        anz_ghosts: 7,
        theme: "crystal",
        reward_exp: 60,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Frostige Falle",
        beschreibung: "Geister bewegen sich schneller auf rutschigem Boden.",
        players: 1,
        map: "fogmaze",
        difficulty: "insane",
        anz_ghosts: 7,
        theme: "ice",
        reward_exp: 65,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: false,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Waldlabyrinth",
        beschreibung: "Enge Gänge, viele Geister – strategisches Bewegen ist Pflicht.",
        players: 1,
        map: "original",
        difficulty: "insane",
        anz_ghosts: 8,
        theme: "forest",
        reward_exp: 70,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: false,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Feuerlabyrinth",
        beschreibung: "Die Geister sind schneller, die Powerups kurzlebiger.",
        players: 1,
        map: "original",
        difficulty: "insane",
        anz_ghosts: 8,
        theme: "lava",
        reward_exp: 75,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Ozeanwellen",
        beschreibung: "Schnelle Reflexe gefordert – Geister bewegen sich unberechenbar.",
        players: 1,
        map: "fogmaze",
        difficulty: "insane",
        anz_ghosts: 9,
        theme: "ocean",
        reward_exp: 80,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: false,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Neonjagd",
        beschreibung: "Bunte Teleporter und schnelle Geister fordern deine Konzentration.",
        players: 1,
        map: "original",
        difficulty: "insane",
        anz_ghosts: 9,
        theme: "neon",
        reward_exp: 85,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Weltraumrennen",
        beschreibung: "Teleport-Strategie ist der Schlüssel – Geister überall.",
        players: 1,
        map: "fogmaze",
        difficulty: "insane",
        anz_ghosts: 10,
        theme: "space",
        reward_exp: 90,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Vulkanchaos",
        beschreibung: "Heiße Teleporter und schnelle Geister – Timing ist alles.",
        players: 1,
        map: "original",
        difficulty: "insane",
        anz_ghosts: 10,
        theme: "volcano",
        reward_exp: 95,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: false,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Kristalllabyrinth II",
        beschreibung: "Noch engere Gänge, noch mehr Geister, Teleporter überall.",
        players: 1,
        map: "crystal",
        difficulty: "insane",
        anz_ghosts: 11,
        theme: "crystal",
        reward_exp: 100,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Mystische Schatten",
        beschreibung: "Dunkle Nebel, viele Geister – nur Meister überleben.",
        players: 1,
        map: "fogmaze",
        difficulty: "insane",
        anz_ghosts: 12,
        theme: "mystic",
        reward_exp: 105,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: false,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Frostige Kristalle",
        beschreibung: "Teleporter überall, schnelle Geister und Powerups – höchste Konzentration gefordert.",
        players: 1,
        map: "crystal",
        difficulty: "insane",
        anz_ghosts: 12,
        theme: "ice",
        reward_exp: 110,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Endgame Challenge I",
        beschreibung: "Viele Geister, Teleporter, Reproduktion – die ultimative Prüfung.",
        players: 1,
        map: "original",
        difficulty: "insane",
        anz_ghosts: 13,
        theme: "lava",
        reward_exp: 120,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Endgame Challenge II",
        beschreibung: "Noch mehr Geister, Teleporter überall, nur Profis schaffen es.",
        players: 1,
        map: "fogmaze",
        difficulty: "insane",
        anz_ghosts: 14,
        theme: "forest",
        reward_exp: 125,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: false,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    },
    {
        name: "Endgame Challenge III",
        beschreibung: "Ultimative Kombination aller Mechaniken – höchste Konzentration nötig.",
        players: 1,
        map: "crystal",
        difficulty: "insane",
        anz_ghosts: 15,
        theme: "crystal",
        reward_exp: 130,
        ghosts_dead: false,
        ghosts_reproduction: true,
        teleporter_aktiv: true,
        teleporter_pacman: true,
        teleporter_ghosts: true,
        aktiv: null,
        abgeschlossen: null
    }

];
